### ISSUE TITLE
Only 1 SSH host can be checked

### ISSUE THREAD

**Issue by gfriloux** [Lex-Persona/SupExt#6]
I have two servers sets for checking.
they will alternately fail on connect : 
```
[INFO] Check dp2_ssh OK (Connected correctly)
[ERROR] Check dp1_ssh KO (Cannot connect to server), retrying in 10 seconds
[INFO] Round of checks finished
[INFO] Check dp1_ssh recovered on second try
[DEBUG] Add entry using cachet for check dp1_ssh
[ERROR] Cachet component DP1 doesn't exist
[ERROR] Cannot update cachet
[INFO] Run new round of checks
[INFO] Running canary checks
[DEBUG] Canary checks finished, running normal checks (from OK locations)
[DEBUG] Add entry using cachet for check dp1_ssh
[ERROR] Cachet component DP1 doesn't exist
[ERROR] Cannot update cachet
[INFO] Check dp1_ssh OK (Connected correctly)
[ERROR] Check dp2_ssh KO (Cannot connect to server), retrying in 10 seconds
[INFO] Round of checks finished
[INFO] Check dp2_ssh recovered on second try
[DEBUG] Add entry using cachet for check dp2_ssh
[ERROR] Cachet component DP2 doesn't exist
[ERROR] Cannot update cachet



[INFO] Run new round of checks
[INFO] Running canary checks
[DEBUG] Canary checks finished, running normal checks (from OK locations)
[DEBUG] Add entry using cachet for check dp2_ssh
[ERROR] Cachet component DP2 doesn't exist
[ERROR] Cannot update cachet
[INFO] Check dp2_ssh OK (Connected correctly)
[ERROR] Check dp1_ssh KO (Cannot connect to server), retrying in 10 seconds
[INFO] Round of checks finished
```

So, if dp1 succeeds, dp2 fails.
dp2 will recover on second check, but then its dp1 that will fail (and recover on second check, and it will loop).

Ignore the Cachet errors, i intentionnally did not set a valid URL, for tests.

**Comment by gfriloux** [comment]
If i set 3 SSH tests, only one will success at a time.

```
[root@Jetdail SupExt]# supext --debug
[INFO] Loading configuration
[DEBUG] Configuration loaded
[INFO] Loading checks and test modules
[DEBUG] Loaded test ssh
[INFO] Loading connector modules
[DEBUG] Loaded connector cachet
[INFO] Loading alerting modules
[DEBUG] Loaded alerting module email

[INFO] Run new round of checks
[INFO] Running canary checks
[DEBUG] Canary checks finished, running normal checks (from OK locations)
[DEBUG] Add entry using cachet for check dp2_ssh
[ERROR] Cachet component DP2 doesn't exist
[ERROR] Cannot update cachet
[INFO] Check dp2_ssh OK (Connected correctly)
[ERROR] Check dp1_ssh KO (Cannot connect to server), retrying in 10 seconds
[ERROR] Check dp3_ssh KO (Cannot connect to server), retrying in 10 seconds
[INFO] Round of checks finished
[INFO] Check dp1_ssh recovered on second try
[DEBUG] Add entry using cachet for check dp1_ssh
[ERROR] Cachet component DP1 doesn't exist
[ERROR] Cannot update cachet
[INFO] Check dp3_ssh recovered on second try
[DEBUG] Add entry using cachet for check dp3_ssh
[ERROR] Cachet component DP3 doesn't exist
[ERROR] Cannot update cachet

[INFO] Run new round of checks
[INFO] Running canary checks
[DEBUG] Canary checks finished, running normal checks (from OK locations)
[ERROR] Check dp1_ssh KO (Cannot connect to server), retrying in 10 seconds
[ERROR] Check dp3_ssh KO (Cannot connect to server), retrying in 10 seconds
[DEBUG] Add entry using cachet for check dp2_ssh
[ERROR] Cachet component DP2 doesn't exist
[ERROR] Cannot update cachet
[INFO] Check dp2_ssh OK (Connected correctly)
[INFO] Round of checks finished
[INFO] Check dp1_ssh recovered on second try
[DEBUG] Add entry using cachet for check dp1_ssh
[ERROR] Cachet component DP1 doesn't exist
[ERROR] Cannot update cachet
[INFO] Check dp3_ssh recovered on second try
[DEBUG] Add entry using cachet for check dp3_ssh
[ERROR] Cachet component DP3 doesn't exist
[ERROR] Cannot update cachet

[INFO] Run new round of checks
[INFO] Running canary checks
[DEBUG] Canary checks finished, running normal checks (from OK locations)
[ERROR] Check dp2_ssh KO (Cannot connect to server), retrying in 10 seconds
[ERROR] Check dp1_ssh KO (Cannot connect to server), retrying in 10 seconds
[DEBUG] Add entry using cachet for check dp3_ssh
[ERROR] Cachet component DP3 doesn't exist
[ERROR] Cannot update cachet
[INFO] Check dp3_ssh OK (Connected correctly)
[INFO] Round of checks finished
```

In this run:
First round : dp2 will succeed, but dp1 and dp3 will fail.
First retry : dp1 and dp3 will recover on second try.
Second round : dp2 will succeed, but dp1 and dp3 will fail.
First retry : dp1 and dp3 will recover on second try.
Third round : DP3 will succeed, but dp1 and dp2 will fail.

**Comment by gfriloux** [comment]
Sometimes, errors from paramiko will show up : 
```
[DEBUG] Canary checks finished, running normal checks (from OK locations)
[ERROR] Check replicant_ssh KO (Cannot connect to server), retrying in 10 seconds
[ERROR] Check dp1_ssh KO (Cannot connect to server), retrying in 10 seconds
[ERROR] Check dp2_ssh KO (Cannot connect to server), retrying in 10 seconds
[DEBUG] Add entry using cachet for check dp3_ssh
[ERROR] Cachet component DP3 doesn't exist
[ERROR] Cannot update cachet
[INFO] Check dp3_ssh OK (Connected correctly)
Exception: Error reading SSH protocol banner[Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 2003, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/packet.py", line 540, in _read_timeout
    x = self.__socket.recv(128)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 1856, in run
    self._check_banner()
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 2008, in _check_banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 9] Bad file descriptor

[ERROR] Check furby_ssh KO (Cannot connect to server), retrying in 10 seconds
Oops, unhandled type 3
```

I believe there is a threading problem.

**Comment by gfriloux** [comment]
This issue can get temporarily fixed by modifying https://github.com/Lex-Persona/SupExt/blob/master/supext/__init__.py#L41 to : 
```python
        self.pool = concurrent.futures.ThreadPoolExecutor(max_workers=1)
```
